# Copyright (c) 2022-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//foundation/ability/ability_runtime/ability_runtime.gni")

config("no_split_lto_unit") {
  cflags = [
    "-fno-split-lto-unit",
    "-fno-lto",
  ]
  ldflags = [ "-fno-lto" ]
}

group("fuzztest") {
  testonly = true

  external_deps = [ "json:nlohmann_json_static" ]
 
  deps = [
    "abilityappdebuginfo_fuzzer:fuzztest",
    "abilityappdebugmanager_fuzzer:fuzztest",
    "abilityappdebugmanagerthird_fuzzer:fuzztest",
    "abilityappdfrapplicationanrlistener_fuzzer:fuzztest",
    "abilityappfreezemanager_fuzzer:fuzztest",
    "abilityappfreezemanagerfifteenth_fuzzer:fuzztest",
    "abilityappfreezemanagerfirst_fuzzer:fuzztest",
    "abilityappfreezemanagerfourteenth_fuzzer:fuzztest",
    "abilityappfreezemanagersecond_fuzzer:fuzztest",
    "abilityappfreezemanagerseventeenth_fuzzer:fuzztest",
    "abilityappfreezemanagersixteenth_fuzzer:fuzztest",
    "abilityappfreezemanagertenth_fuzzer:fuzztest",
    "abilityappfreezemanagerthird_fuzzer:fuzztest",
    "abilityappjsheapmeminfo_fuzzer:fuzztest",
    "abilityappmgrapprunningmanager_fuzzer:fuzztest",
    "abilityappmgrevent_fuzzer:fuzztest",
    "abilityappmgreventfourth_fuzzer:fuzztest",
    "abilityappmgrpagestatedata_fuzzer:fuzztest",
    "abilityappmgrrenderstatedata_fuzzer:fuzztest",
    "abilityappmgrrenderstateobservermanager_fuzzer:fuzztest",
    "abilityappmgrrunningmultiinfo_fuzzer:fuzztest",
    "abilityapppreloader_fuzzer:fuzztest",
    "abilityapppreloaderfourth_fuzzer:fuzztest",
    "abilityapppreloaderthird_fuzzer:fuzztest",
    "abilityattachtimeout_fuzzer:fuzztest",
    "abilityautostartupclient_fuzzer:fuzztest",
    "abilityautostartupclientfirst_fuzzer:fuzztest",
    "abilityautostartupclientsecond_fuzzer:fuzztest",
    "abilityautostartupclientthird_fuzzer:fuzztest",
    "abilityautostartupdatamanager_fuzzer:fuzztest",
    "abilityautostartupdatamanagera_fuzzer:fuzztest",
    "abilityautostartupdatamanagerb_fuzzer:fuzztest",
    "abilityautostartupdatamanagerfifth_fuzzer:fuzztest",
    "abilityautostartupdatamanagerfourth_fuzzer:fuzztest",
    "abilityautostartupdatamanagerthird_fuzzer:fuzztest",
    "abilityautostartupservicea_fuzzer:fuzztest",
    "abilityautostartupserviceb_fuzzer:fuzztest",
    "abilityautostartupservicec_fuzzer:fuzztest",
    "abilityautostartupservicefirst_fuzzer:fuzztest",
    "abilitybackgroundconnection_fuzzer:fuzztest",
    "abilitycachemanagera_fuzzer:fuzztest",
    "abilityconnectionstub_fuzzer:fuzztest",
    "abilityconnectionstubremaining_fuzzer:fuzztest",
    # "abilityconnectmanager_fuzzer:fuzztest",
    "abilitycontext_fuzzer:fuzztest",
    "abilitycontrollerstub_fuzzer:fuzztest",
    "abilitydebugdeal_fuzzer:fuzztest",
    "abilitydebugdealfirst_fuzzer:fuzztest",
    "abilitydebugresponseproxy_fuzzer:fuzztest",
    "abilitydebugresponsestub_fuzzer:fuzztest",
    "abilitydebugresponsestubremaining_fuzzer:fuzztest",
    "abilityecologicalrulemgrservicefirst_fuzzer:fuzztest",
    "abilityeventhandler_fuzzer:fuzztest",
    "abilityeventutil_fuzzer:fuzztest",
    "abilityfirstframestateobservermanager_fuzzer:fuzztest",
    "abilityfirstframestateobserverstub_fuzzer:fuzztest",
    "abilityforegroundstateobserverproxy_fuzzer:fuzztest",
    "abilityforegroundstateobserverstub_fuzzer:fuzztest",
    "abilityframeworkscjenvironment_fuzzer:fuzztest",
    "abilityframeworksnativejsworker_fuzzer:fuzztest",
    "abilityframeworksnativeohosjsenvlogger_fuzzer:fuzztest",
    "abilityinfocallbackstub_fuzzer:fuzztest",
    "abilityinfocallbackstubremaining_fuzzer:fuzztest",
    "abilityinterfacesappmgrabilitydebugresponseproxy_fuzzer:fuzztest",
    "abilityinterfacesappmgrappdebuglistenerproxy_fuzzer:fuzztest",
    "abilityinterfacesappmgrappdebuglistenerstub_fuzzer:fuzztest",
    "abilityinterfacesappmgrappforegroundstateobserverstub_fuzzer:fuzztest",
    "abilityinterfacesappmgrchildschedulerproxy_fuzzer:fuzztest",
    "abilityinterfacesappmgrchildschedulerstub_fuzzer:fuzztest",
    "abilityinterfacesappmgrnativechildnotifyproxy_fuzzer:fuzztest",
    "abilityinterfacesappmgrnativechildnotifystub_fuzzer:fuzztest",
    "abilityinterfacesappmgrrenderstateobserverstub_fuzzer:fuzztest",
    "abilitykeepalivedatamanager_fuzzer:fuzztest",
    "abilitykeepaliveservice_fuzzer:fuzztest",
    # "abilitymanagereventsubscriber_fuzzer:fuzztest",
    "abilitymanagerradar_fuzzer:fuzztest",
    "abilitymanagerservicea_fuzzer:fuzztest",
    "abilitymanagerserviceb_fuzzer:fuzztest",
    "abilitymanagerservicec_fuzzer:fuzztest",
    "abilitymanagerserviced_fuzzer:fuzztest",
    "abilitymanagerservicee_fuzzer:fuzztest",
    "abilitymanagerserviceeighth_fuzzer:fuzztest",
    "abilitymanagerservicef_fuzzer:fuzztest",
    "abilitymanagerservicefifth_fuzzer:fuzztest",
    "abilitymanagerservicefirst_fuzzer:fuzztest",
    "abilitymanagerservicefourth_fuzzer:fuzztest",
    "abilitymanagerserviceg_fuzzer:fuzztest",
    "abilitymanagerserviceh_fuzzer:fuzztest",
    "abilitymanagerserviceninth_fuzzer:fuzztest",
    "abilitymanagerservicesecond_fuzzer:fuzztest",
    "abilitymanagerserviceseventh_fuzzer:fuzztest",
    "abilitymanagerservicesixth_fuzzer:fuzztest",
    "abilitymanagerservicetenth_fuzzer:fuzztest",
    "abilitymanagerservicethird_fuzzer:fuzztest",
    "abilitymanagerstubautostart_fuzzer:fuzztest",
    "abilitymanagerstubconnect_fuzzer:fuzztest",
    "abilitymanagerstubdebug_fuzzer:fuzztest",
    "abilitymanagerstubdms_fuzzer:fuzztest",
    "abilitymanagerstublifecycle_fuzzer:fuzztest",
    "abilitymanagerstubmission_fuzzer:fuzztest",
    "abilitymanagerstubpending_fuzzer:fuzztest",
    "abilitymanagerstubremaining10_fuzzer:fuzztest",
    "abilitymanagerstubremaining11_fuzzer:fuzztest",
    "abilitymanagerstubremaining12_fuzzer:fuzztest",
    "abilitymanagerstubremaining13_fuzzer:fuzztest",
    "abilitymanagerstubremaining14_fuzzer:fuzztest",
    "abilitymanagerstubremaining1_fuzzer:fuzztest",
    "abilitymanagerstubremaining2_fuzzer:fuzztest",
    "abilitymanagerstubremaining3_fuzzer:fuzztest",
    "abilitymanagerstubremaining4_fuzzer:fuzztest",
    "abilitymanagerstubremaining5_fuzzer:fuzztest",
    "abilitymanagerstubremaining6_fuzzer:fuzztest",
    "abilitymanagerstubremaining7_fuzzer:fuzztest",
    "abilitymanagerstubremaining8_fuzzer:fuzztest",
    "abilitymanagerstubremaining9_fuzzer:fuzztest",
    "abilitymanagerstubselfstart_fuzzer:fuzztest",
    "abilitymanagerstubservice_fuzzer:fuzztest",
    "abilitymanagerstubstart_fuzzer:fuzztest",
    "abilitymanagerstubstartextra_fuzzer:fuzztest",
    "abilitymanagerstubterminate_fuzzer:fuzztest",
    "abilitymemorylevelinfo_fuzzer:fuzztest",
    "abilitymgrabilitymanagerstub_fuzzer:fuzztest",
    "abilitymgrappexitreasonhelper_fuzzer:fuzztest",
    "abilitymgrappexitreasonhelpersecond_fuzzer:fuzztest",
    "abilitymgrcontrolinterceptor_fuzzer:fuzztest",
    "abilitymgrdisposedruleinterceptor_fuzzer:fuzztest",
    "abilitymgrecologicalruleinterceptor_fuzzer:fuzztest",
    "abilitymgrecologicalruleinterceptorfirst_fuzzer:fuzztest",
    "abilitymgrecologicalruleinterceptorsecond_fuzzer:fuzztest",
    "abilitymgrecologicalrulemgrserviceparam_fuzzer:fuzztest",
    "abilitymgrextensionrecord_fuzzer:fuzztest",
    "abilitymgrinsightintentexecutemanager_fuzzer:fuzztest",
    "abilitymgrinsightintentexecuteresult_fuzzer:fuzztest",
    "abilitymgrinsightintentutils_fuzzer:fuzztest",
    "abilitymgrinterceptorexecuter_fuzzer:fuzztest",
    "abilitymgrpreloaduiextstateobserver_fuzzer:fuzztest",
    "abilitymgrrdbparserutil_fuzzer:fuzztest",
    "abilitymgrrest_fuzzer:fuzztest",
    "abilitymgrrestartappmanager_fuzzer:fuzztest",
    "abilitymgruiextensionrecord_fuzzer:fuzztest",
    "abilitymgruiextensionsessioninfo_fuzzer:fuzztest",
    "abilitypermissionutil_fuzzer:fuzztest",
    "abilityprocessoptions_fuzzer:fuzztest",
    "abilityresidentprocessrdb_fuzzer:fuzztest",
    "abilityrunningrecord_fuzzer:fuzztest",
    "abilityschedulerstub_fuzzer:fuzztest",
    "abilityschedulerstubremaining_fuzzer:fuzztest",
    "abilitystartwithwaitdata_fuzzer:fuzztest",
    "abilitystartwithwaitobservermanager_fuzzer:fuzztest",
    "abilitystartwithwaitobserverproxy_fuzzer:fuzztest",
    "abilitystartwithwaitobserverstub_fuzzer:fuzztest",
    "abilitystubabilityrecovery_fuzzer:fuzztest",
    "abilitystubabilityrecoveryenable_fuzzer:fuzztest",
    "abilitystubabilitytransitiondone_fuzzer:fuzztest",
    "abilitystubacquiredataability_fuzzer:fuzztest",
    "abilitystubacquiresharedata_fuzzer:fuzztest",
    "abilitystubaddfreeinstallobserver_fuzzer:fuzztest",
    "abilitystubaddwindowinfodone_fuzzer:fuzztest",
    "abilitystubattachabilitythread_fuzzer:fuzztest",
    "abilitystubattachappdebug_fuzzer:fuzztest",
    "abilitystubcallrequestdone_fuzzer:fuzztest",
    "abilitystubcalluiabilitybyscb_fuzzer:fuzztest",
    "abilitystubcancelwantsender_fuzzer:fuzztest",
    "abilitystubchangefocusabilitydone_fuzzer:fuzztest",
    "abilitystubcheckuiextensionisfocused_fuzzer:fuzztest",
    "abilitystubcleanallmissions_fuzzer:fuzztest",
    "abilitystubcleanmission_fuzzer:fuzztest",
    "abilitystubclosemultiwindowdone_fuzzer:fuzztest",
    "abilitystubcloseuiabilitybyscb_fuzzer:fuzztest",
    "abilitystubcommandabilitydone_fuzzer:fuzztest",
    "abilitystubcommandabilitywindowdone_fuzzer:fuzztest",
    "abilitystubcompelverifypermissiondone_fuzzer:fuzztest",
    "abilitystubcompletefirstframedrawing_fuzzer:fuzztest",
    "abilitystubconnectability_fuzzer:fuzztest",
    "abilitystubconnectabilitydone_fuzzer:fuzztest",
    "abilitystubconnectabilitywithtype_fuzzer:fuzztest",
    "abilitystubconnectuiextensionability_fuzzer:fuzztest",
    "abilitystubcontinueability_fuzzer:fuzztest",
    "abilitystubcontinuemission_fuzzer:fuzztest",
    "abilitystubcontinuemissionofbundlename_fuzzer:fuzztest",
    "abilitystubdelegatordoabilitybackground_fuzzer:fuzztest",
    "abilitystubdelegatordoabilityforeground_fuzzer:fuzztest",
    "abilitystubdetachappdebug_fuzzer:fuzztest",
    "abilitystubdisconnectability_fuzzer:fuzztest",
    "abilitystubdisconnectabilitydone_fuzzer:fuzztest",
    "abilitystubdoabilitybackground_fuzzer:fuzztest",
    "abilitystubdoabilityforeground_fuzzer:fuzztest",
    "abilitystubdumpabilityinfodone_fuzzer:fuzztest",
    "abilitystubdumpstate_fuzzer:fuzztest",
    "abilitystubdumpsysstate_fuzzer:fuzztest",
    "abilitystubexecuteinsightintentdone_fuzzer:fuzztest",
    "abilitystubexecuteintent_fuzzer:fuzztest",
    "abilitystubfinishusertest_fuzzer:fuzztest",
    "abilitystubforceexitapp_fuzzer:fuzztest",
    "abilitystubfreeinstallabilityfromremote_fuzzer:fuzztest",
    "abilitystubgetabilityrunninginfo_fuzzer:fuzztest",
    "abilitystubgetabilitystatebypersistentid_fuzzer:fuzztest",
    "abilitystubgetabilitytoken_fuzzer:fuzztest",
    "abilitystubgetappmemorysize_fuzzer:fuzztest",
    "abilitystubgetdlpconnectioninfos_fuzzer:fuzztest",
    "abilitystubgetelementnamebytoken_fuzzer:fuzztest",
    "abilitystubgetextensionrunninginfo_fuzzer:fuzztest",
    "abilitystubgetfloatingmissionsdone_fuzzer:fuzztest",
    "abilitystubgetmissionidbytoken_fuzzer:fuzztest",
    "abilitystubgetmissioninfo_fuzzer:fuzztest",
    "abilitystubgetmissioninfos_fuzzer:fuzztest",
    "abilitystubgetmissionlockmodestatedone_fuzzer:fuzztest",
    # "abilitystubgetmissionsnapshot_fuzzer:fuzztest",
    # "abilitystubgetmissionsnapshotbyid_fuzzer:fuzztest",
    "abilitystubgetmissionsnapshotinfo_fuzzer:fuzztest",
    "abilitystubgetpendingrequestwant_fuzzer:fuzztest",
    "abilitystubgetpendingwantbundlename_fuzzer:fuzztest",
    "abilitystubgetpendingwantcode_fuzzer:fuzztest",
    "abilitystubgetpendingwanttype_fuzzer:fuzztest",
    "abilitystubgetpendingwantuid_fuzzer:fuzztest",
    "abilitystubgetpendingwantuserid_fuzzer:fuzztest",
    "abilitystubgetprocessrunninginfo_fuzzer:fuzztest",
    "abilitystubgetrecentmissiondone_fuzzer:fuzztest",
    "abilitystubgettopability_fuzzer:fuzztest",
    "abilitystubgettopabilitytoken_fuzzer:fuzztest",
    "abilitystubgetwantsender_fuzzer:fuzztest",
    "abilitystubgetwantsendinfo_fuzzer:fuzztest",
    "abilitystubinterface_fuzzer:fuzztest",
    "abilitystubisramconstraineddevice_fuzzer:fuzztest",
    "abilitystubisrunninginstabilitytest_fuzzer:fuzztest",
    "abilitystubkillprocess_fuzzer:fuzztest",
    # "abilitystubkillprocesswithprepareterminatedone_fuzzer:fuzztest",
    "abilitystubliststackinfodone_fuzzer:fuzztest",
    "abilitystublockmissionforcleanup_fuzzer:fuzztest",
    "abilitystublogoutuser_fuzzer:fuzztest",
    "abilitystubluckmissiondone_fuzzer:fuzztest",
    "abilitystubmaximizemultiwindowdone_fuzzer:fuzztest",
    "abilitystubminimizeability_fuzzer:fuzztest",
    "abilitystubminimizeabilitydone_fuzzer:fuzztest",
    "abilitystubminimizemultiwindowdone_fuzzer:fuzztest",
    "abilitystubminimizeuiabilitybyscb_fuzzer:fuzztest",
    "abilitystubminimizeuiextensionability_fuzzer:fuzztest",
    "abilitystubmoveabilitytobackground_fuzzer:fuzztest",
    "abilitystubmovemissionstobackground_fuzzer:fuzztest",
    "abilitystubmovemissionstoforeground_fuzzer:fuzztest",
    "abilitystubmovemissiontoenddone_fuzzer:fuzztest",
    "abilitystubmovemissiontofront_fuzzer:fuzztest",
    "abilitystubmovemissiontofrontbyoptions_fuzzer:fuzztest",
    "abilitystubmovemissiontosplitscreenstackdone_fuzzer:fuzztest",
    "abilitystubmovemissiontotopdone_fuzzer:fuzztest",
    "abilitystubnotifycompletecontinuation_fuzzer:fuzztest",
    "abilitystubnotifycontinuationresult_fuzzer:fuzztest",
    "abilitystubnotifysaveasresult_fuzzer:fuzztest",
    "abilitystubpoweroffdone_fuzzer:fuzztest",
    "abilitystubpowerondone_fuzzer:fuzztest",
    "abilitystubprepareterminateability_fuzzer:fuzztest",
    # "abilitystubprepareterminateabilitydone_fuzzer:fuzztest",
    "abilitystubquerymissionvaild_fuzzer:fuzztest",
    # "abilitystubquerypreloaduiextensionrecord_fuzzer:fuzztest",
    "abilitystubrecordappexitreason_fuzzer:fuzztest",
    # "abilitystubregisterabilityfirstframestateobserver_fuzzer:fuzztest",
    "abilitystubregisterappdebuglistener_fuzzer:fuzztest",
    "abilitystubregistercancellistener_fuzzer:fuzztest",
    "abilitystubregistercollaborator_fuzzer:fuzztest",
    "abilitystubregisterconnectionobserver_fuzzer:fuzztest",
    "abilitystubregistermissionlistener_fuzzer:fuzztest",
    "abilitystubregisterremotemissionlistener_fuzzer:fuzztest",
    "abilitystubregisterremoteofflistener_fuzzer:fuzztest",
    "abilitystubregisterremoteonlistener_fuzzer:fuzztest",
    # "abilitystubregistersessionhandler_fuzzer:fuzztest",
    "abilitystubregisterwmshandler_fuzzer:fuzztest",
    "abilitystubreleasecallability_fuzzer:fuzztest",
    "abilitystubreleasedataability_fuzzer:fuzztest",
    "abilitystubremovemissiondone_fuzzer:fuzztest",
    "abilitystubremovestackdone_fuzzer:fuzztest",
    "abilitystubreportdrawncompleted_fuzzer:fuzztest",
    "abilitystubrequestdialogservice_fuzzer:fuzztest",
    "abilitystubsendanrprocessid_fuzzer:fuzztest",
    "abilitystubsendresulttoability_fuzzer:fuzztest",
    "abilitystubsendwantsender_fuzzer:fuzztest",
    "abilitystubsetabilitycontroller_fuzzer:fuzztest",
    "abilitystubsetmissioncontinuestate_fuzzer:fuzztest",
    "abilitystubsetmissionicon_fuzzer:fuzztest",
    "abilitystubsetmissioninfodone_fuzzer:fuzztest",
    "abilitystubsetmissionlabel_fuzzer:fuzztest",
    "abilitystubsetrootscenesession_fuzzer:fuzztest",
    "abilitystubsetsessionlockedstate_fuzzer:fuzztest",
    "abilitystubsetsessionmanagerservice_fuzzer:fuzztest",
    "abilitystubsharedatadone_fuzzer:fuzztest",
    "abilitystubstartability_fuzzer:fuzztest",
    "abilitystubstartabilityaddcaller_fuzzer:fuzztest",
    "abilitystubstartabilityascallerbytoken_fuzzer:fuzztest",
    "abilitystubstartabilityascallerforoptions_fuzzer:fuzztest",
    "abilitystubstartabilitybycall_fuzzer:fuzztest",
    "abilitystubstartabilityforoptions_fuzzer:fuzztest",
    "abilitystubstartabilityforsettings_fuzzer:fuzztest",
    "abilitystubstartcontinuation_fuzzer:fuzztest",
    "abilitystubstartextensionability_fuzzer:fuzztest",
    "abilitystubstartspecifiedabilitybyscb_fuzzer:fuzztest",
    "abilitystubstartsyncmissions_fuzzer:fuzztest",
    "abilitystubstartuiabilitybyscb_fuzzer:fuzztest",
    "abilitystubstartuiextensionability_fuzzer:fuzztest",
    "abilitystubstartuser_fuzzer:fuzztest",
    "abilitystubstartusertest_fuzzer:fuzztest",
    "abilitystubstopextensionability_fuzzer:fuzztest",
    "abilitystubstopserviceability_fuzzer:fuzztest",
    "abilitystubstopsyncmissions_fuzzer:fuzztest",
    "abilitystubstopuser_fuzzer:fuzztest",
    "abilitystubterminateability_fuzzer:fuzztest",
    "abilitystubterminateuiextensionability_fuzzer:fuzztest",
    "abilitystubtomoveabilitytobackground_fuzzer:fuzztest",
    "abilitystubuninstallapp_fuzzer:fuzztest",
    "abilitystubunlockmissionforcleanup_fuzzer:fuzztest",
    "abilitystubunluckmissiondone_fuzzer:fuzztest",
    # "abilitystubunregisterabilityfirstframestateobserver_fuzzer:fuzztest",
    "abilitystubunregisterappdebuglistener_fuzzer:fuzztest",
    "abilitystubunregistercancellistener_fuzzer:fuzztest",
    "abilitystubunregistercollaborator_fuzzer:fuzztest",
    "abilitystubunregisterconnectionobserver_fuzzer:fuzztest",
    "abilitystubunregistermissionlistener_fuzzer:fuzztest",
    "abilitystubunregisterremotemissionlistener_fuzzer:fuzztest",
    "abilitystubupdatemissionsnapshotfromwms_fuzzer:fuzztest",
    "abilitystubverifypermission_fuzzer:fuzztest",
    "abilitytokenstub_fuzzer:fuzztest",
    "abilitytransitiondone_fuzzer:fuzztest",
    "abilityuriextensionhostinfo_fuzzer:fuzztest",
    "acquiredataability_fuzzer:fuzztest",
    "acquiresharedatacallbackstub_fuzzer:fuzztest",
    "addabilitystagedone_fuzzer:fuzztest",
    "amsmanager_fuzzer:fuzztest",
    "amsmgrscheduler_fuzzer:fuzztest",
    "amsmgrstubdebug_fuzzer:fuzztest",
    "amsmgrstubkill_fuzzer:fuzztest",
    "amsmgrstublifecycle_fuzzer:fuzztest",
    "amsmgrstubmisc_fuzzer:fuzztest",
    "appforegroundstateobserverproxy_fuzzer:fuzztest",
    "appfreezeutil_fuzzer:fuzztest",
    "applicationanrlistener_fuzzer:fuzztest",
    "applicationstateobserverstub_fuzzer:fuzztest",
    "applifecycledeal_fuzzer:fuzztest",
    "appmanager_fuzzer:fuzztest",
    "appmgrclientrest_fuzzer:fuzztest",
    "appmgrrest_fuzzer:fuzztest",
    # "appmgrservicefirst_fuzzer:fuzztest",
    "appmgrstub_fuzzer:fuzztest",
    "appmgrstubchild_fuzzer:fuzztest",
    # "appmgrstubextra_fuzzer:fuzztest",
    # "appmgrstubfield_fuzzer:fuzztest",
    "appmgrstubforegroundapps_fuzzer:fuzztest",
    "appmgrstubmemory_fuzzer:fuzztest",
    "appmgrstubprocess_fuzzer:fuzztest",
    "appmgrstubremaining1_fuzzer:fuzztest",
    "appmgrstubremaining2_fuzzer:fuzztest",
    "appmgrstubremaining3_fuzzer:fuzztest",
    "appmgrstubremaining4_fuzzer:fuzztest",
    "appmgrstubremaining5_fuzzer:fuzztest",
    "appmgrstubremaining6_fuzzer:fuzztest",
    "appmgrstubrunninginfo_fuzzer:fuzztest",
    "appmgrstubselfinstancekeys_fuzzer:fuzztest",
    "appmgrstubstate_fuzzer:fuzztest",
    "apprunningstatusproxy_fuzzer:fuzztest",
    "apprunningstatusstub_fuzzer:fuzztest",
    "appschedulerhost_fuzzer:fuzztest",
    "appstatecallbackhost_fuzzer:fuzztest",
    "appstateobservermanager_fuzzer:fuzztest",
    "assertfaultcallbackdeathmgr_fuzzer:fuzztest",
    "assertfaultcallbackstub_fuzzer:fuzztest",
    "assertfaultproxy_fuzzer:fuzztest",
    "atomicservicestatuscallbackstub_fuzzer:fuzztest",
    "attachabilitythread_fuzzer:fuzztest",
    "attachrenderprocess_fuzzer:fuzztest",
    # "autostartupcallbackstub_fuzzer:fuzztest",
    "autostartupinfo_fuzzer:fuzztest",
    "bundlemgrhelper_fuzzer:fuzztest",
    "bundlemgrhelperfifth_fuzzer:fuzztest",
    "bundlemgrhelperfirst_fuzzer:fuzztest",
    "bundlemgrhelpersecond_fuzzer:fuzztest",
    "cacheprocessmanagera_fuzzer:fuzztest",
    "cacheprocessmanagerb_fuzzer:fuzztest",
    "cancelwantsender_fuzzer:fuzztest",
    "cleanallmissions_fuzzer:fuzztest",
    "cleanmission_fuzzer:fuzztest",
    "clearupapplicationdata_fuzzer:fuzztest",
    "closeability_fuzzer:fuzztest",
    "completefirstframedrawing_fuzzer:fuzztest",
    "configurationobserverstub_fuzzer:fuzztest",
    "connectability_fuzzer:fuzztest",
    "connectcallbackstub_fuzzer:fuzztest",
    "connectionobserverclient_fuzzer:fuzztest",
    # "connectionobserverclientimpl_fuzzer:fuzztest",
    "connectionobserverclientimplfifth_fuzzer:fuzztest",
    "connectionobserverclientimplfourth_fuzzer:fuzztest",
    "connectionobserverclientimplthird_fuzzer:fuzztest",
    "connectionobserverstub_fuzzer:fuzztest",
    "connectionstatemanager_fuzzer:fuzztest",
    "continueability_fuzzer:fuzztest",
    "continuemission_fuzzer:fuzztest",
    "crowdtestinterceptor_fuzzer:fuzztest",
    "dataabilitymanager_fuzzer:fuzztest",
    "dataabilityobserverstub_fuzzer:fuzztest",
    "dataabilityrecord_fuzzer:fuzztest",
    "dataabilityrecordfirst_fuzzer:fuzztest",
    "dataabilityrecordsecond_fuzzer:fuzztest",
    "dataobsmgrclient_fuzzer:fuzztest",
    "dataobsmgrstub_fuzzer:fuzztest",
    "deeplinkreserveconfig_fuzzer:fuzztest",
    "delegatordoabilityforeground_fuzzer:fuzztest",
    "dialogsessioninfo_fuzzer:fuzztest",
    "dialogsessionmanager_fuzzer:fuzztest",
    "dialogsessionmanagerfirst_fuzzer:fuzztest",
    "dialogsessionmanagersecond_fuzzer:fuzztest",
    "disposedobserver_fuzzer:fuzztest",
    "doabilitybackground_fuzzer:fuzztest",
    "doabilityforeground_fuzzer:fuzztest",
    "dumpabilityinfodone_fuzzer:fuzztest",
    "dumpstate_fuzzer:fuzztest",
    "dumpsysstate_fuzzer:fuzztest",
    "exitinfodatamanagerfirst_fuzzer:fuzztest",
    "exitinfodatamanagersecond_fuzzer:fuzztest",
    "exitreason_fuzzer:fuzztest",
    "extensionconfig_fuzzer:fuzztest",
    "extensioncontrolinterceptor_fuzzer:fuzztest",
    "extensioncontrolinterceptorfirst_fuzzer:fuzztest",
    "extensioncontrolinterceptorsecond_fuzzer:fuzztest",
    "extensionloadparam_fuzzer:fuzztest",
    "extensionmanagerclient_fuzzer:fuzztest",
    "extensionpermissionsutil_fuzzer:fuzztest",
    "extensionrecordfactory_fuzzer:fuzztest",
    "extensionrecordmanager_fuzzer:fuzztest",
    "extensionrecordmanagera_fuzzer:fuzztest",
    "extensionrecordmanagerb_fuzzer:fuzztest",
    "extensionrecordmanagerc_fuzzer:fuzztest",
    "extensionrunningtimeoutmonitor_fuzzer:fuzztest",
    "extractinsightintentprofile_fuzzer:fuzztest",
    "faultdata_fuzzer:fuzztest",
    "forcetimeoutfortest_fuzzer:fuzztest",
    "foregroundappconnectionclient_fuzzer:fuzztest",
    "foregroundappconnectionstub_fuzzer:fuzztest",
    "freeinstallabilityfromremote_fuzzer:fuzztest",
    "freeinstallobserverstub_fuzzer:fuzztest",
    "freezeutil_fuzzer:fuzztest",
    # "getabilityrunninginfos_fuzzer:fuzztest",
    "getapplicationinfobyprocessid_fuzzer:fuzztest",
    "getappmemorysize_fuzzer:fuzztest",
    "getconfiguration_fuzzer:fuzztest",
    "getmissionidbytoken_fuzzer:fuzztest",
    "getmissioninfos_fuzzer:fuzztest",
    # "getprocessrunninginfos_fuzzer:fuzztest",
    "getprocessrunninginfosbyuserid_fuzzer:fuzztest",
    "getrunningprocessinfobytoken_fuzzer:fuzztest",
    "getwantsender_fuzzer:fuzztest",
    "handledlpapp_fuzzer:fuzztest",
    "hiddenstartobserverstub_fuzzer:fuzztest",
    "hiddenstartutils_fuzzer:fuzztest",
    "imageerrorhandlerstub_fuzzer:fuzztest",
    "imageprocessstateobserverstub_fuzzer:fuzztest",
    "insightintentdbcache_fuzzer:fuzztest",
    "insightintentdbcachefirst_fuzzer:fuzztest",
    "insightintentexecutecallbackstub_fuzzer:fuzztest",
    "insightintentexecutemanagerfirst_fuzzer:fuzztest",
    "insightintentexecutemanagersecond_fuzzer:fuzztest",
    "insightintentexecutemanagerthird_fuzzer:fuzztest",
    "insightintentexecuteparamfourth_fuzzer:fuzztest",
    "insightintentexecuteparamsecond_fuzzer:fuzztest",
    "insightintentexecuteparamthird_fuzzer:fuzztest",
    "insightintentrdbdatamanagerthird_fuzzer:fuzztest",
    "insightintentrdbstoragemgr_fuzzer:fuzztest",
    "insightintentutilsfirst_fuzzer:fuzztest",
    "insightintentutilsfourth_fuzzer:fuzztest",
    "insightintentutilssecond_fuzzer:fuzztest",
    "insightintentutilsthird_fuzzer:fuzztest",
    "intentclient_fuzzer:fuzztest",
    "isramconstraineddevice_fuzzer:fuzztest",
    "jsabilityautostartupmanager_fuzzer:fuzztest",
    "keepaliveprocessmanagerfirst_fuzzer:fuzztest",
    "keepaliveprocessmanagersecond_fuzzer:fuzztest",
    "keepaliveprocessmanagerthird_fuzzer:fuzztest",
    "kiainterceptorstub_fuzzer:fuzztest",
    "killapplication_fuzzer:fuzztest",
    "killapplicationself_fuzzer:fuzztest",
    "killprocessbyabilitytoken_fuzzer:fuzztest",
    "killprocessesbybundlename_fuzzer:fuzztest",
    "killprocessesbyuserid_fuzzer:fuzztest",
    "loadability_fuzzer:fuzztest",
    "loadabilitycallbackstub_fuzzer:fuzztest",
    "localpendingwant_fuzzer:fuzztest",
    "localpendingwantfirst_fuzzer:fuzztest",
    "lockmissionforcleanup_fuzzer:fuzztest",
    "mainelementutils_fuzzer:fuzztest",
    "mainelementutilsfirst_fuzzer:fuzztest",
    "mainelementutilssecond_fuzzer:fuzztest",
    "memdumpcallbackstub_fuzzer:fuzztest",
    "minimizeability_fuzzer:fuzztest",
    "missiondatastorage_fuzzer:fuzztest",
    "missioninfo_fuzzer:fuzztest",
    "missioninfomgra_fuzzer:fuzztest",
    "missioninfomgrb_fuzzer:fuzztest",
    "missioninfomgrc_fuzzer:fuzztest",
    "missionlistenercontroller_fuzzer:fuzztest",
    "missionlistenerstub_fuzzer:fuzztest",
    "missionlistmanagerfirst_fuzzer:fuzztest",
    "missionlistmanagerfourth_fuzzer:fuzztest",
    "missionlistmanagersecond_fuzzer:fuzztest",
    "missionlistmanagerthird_fuzzer:fuzztest",
    "missionmanagerclient_fuzzer:fuzztest",
    "missionsnapshot_fuzzer:fuzztest",
    "missionvalidresult_fuzzer:fuzztest",
    "modulerunningrecord_fuzzer:fuzztest",
    "multiinstanceutils_fuzzer:fuzztest",
    "multiuserconfigmgr_fuzzer:fuzztest",
    "nativechildnotifystubremaining_fuzzer:fuzztest",
    "notifycompletecontinuation_fuzzer:fuzztest",
    "notifycontinuationresult_fuzzer:fuzztest",
    "notifymemorylevel_fuzzer:fuzztest",
    "observerstubfield_fuzzer:fuzztest",
    "observerstubfieldremaining_fuzzer:fuzztest",
    "openlinkoptions_fuzzer:fuzztest",
    "pendingwantmanager_fuzzer:fuzztest",
    "preloaduiextensionexecutecallbackstub_fuzzer:fuzztest",
    "preloaduiextstateobserver_fuzzer:fuzztest",
    "prepareterminate_fuzzer:fuzztest",
    "prepareterminatecallbackstub_fuzzer:fuzztest",
    "prestartnwebspawnprocess_fuzzer:fuzztest",
    "queryermsobserverstub_fuzzer:fuzztest",
    "quickfixcallbackstub_fuzzer:fuzztest",
    "quickfixmanagerclient_fuzzer:fuzztest",
    "quickfixmanagerstub_fuzzer:fuzztest",
    "rdbdatamanagerfourth_fuzzer:fuzztest",
    "rdbdatamanagersecond_fuzzer:fuzztest",
    "registerabilitylifecyclecallback_fuzzer:fuzztest",
    "registerconfigurationobserver_fuzzer:fuzztest",
    "registerenvironmentcallback_fuzzer:fuzztest",
    "registermissionlistener_fuzzer:fuzztest",
    "releasedataability_fuzzer:fuzztest",
    "remoteintentresultcallbackstub_fuzzer:fuzztest",
    "remotemissionlistenerstub_fuzzer:fuzztest",
    "remoteonlistenerstub_fuzzer:fuzztest",
    "remoteregisterservicestub_fuzzer:fuzztest",
    "renderschedulerhost_fuzzer:fuzztest",
    "renderstateobserverproxy_fuzzer:fuzztest",
    "requeststartabilitycallbackstub_fuzzer:fuzztest",
    "residentprocessmanagereighth_fuzzer:fuzztest",
    "residentprocessmanagereleven_fuzzer:fuzztest",
    "residentprocessmanagerfifth_fuzzer:fuzztest",
    "residentprocessmanagerfirst_fuzzer:fuzztest",
    "residentprocessmanagerfourth_fuzzer:fuzztest",
    "residentprocessmanagerninth_fuzzer:fuzztest",
    "residentprocessmanagersecond_fuzzer:fuzztest",
    "residentprocessmanagerseventh_fuzzer:fuzztest",
    "residentprocessmanagersixth_fuzzer:fuzztest",
    "residentprocessmanagertenth_fuzzer:fuzztest",
    "residentprocessmanagerthird_fuzzer:fuzztest",
    "residentprocessmanagerthirteenth_fuzzer:fuzztest",
    "residentprocessmanagertwelfth_fuzzer:fuzztest",
    "scheduleacceptwantdone_fuzzer:fuzztest",
    "schedulecommandabilitydone_fuzzer:fuzztest",
    "scheduleconnectabilitydone_fuzzer:fuzztest",
    "scheduledisconnectabilitydone_fuzzer:fuzztest",
    "sendresulttoability_fuzzer:fuzztest",
    # "sessionhandlerstub_fuzzer:fuzztest",
    "setabilitycontroller_fuzzer:fuzztest",
    "setmissioncontinuestate_fuzzer:fuzztest",
    "setmissionicon_fuzzer:fuzztest",
    "setmissionlabel_fuzzer:fuzztest",
    "skillexecutecallbackstub_fuzzer:fuzztest",
    "startability_fuzzer:fuzztest",
    "startabilitybycall_fuzzer:fuzztest",
    "startabilityutils_fuzzer:fuzztest",
    "startabilityutilsfirst_fuzzer:fuzztest",
    "startcontinuation_fuzzer:fuzztest",
    "startoptionsutils_fuzzer:fuzztest",
    "startoptionsutilsfirst_fuzzer:fuzztest",
    "startrenderprocess_fuzzer:fuzztest",
    "startserviceextensionability_fuzzer:fuzztest",
    "startspecifiedability_fuzzer:fuzztest",
    "startspecifiedabilityresponsestub_fuzzer:fuzztest",
    "startsyncremotemissions_fuzzer:fuzztest",
    # "startupresidentprocess_fuzzer:fuzztest",
    "startuser_fuzzer:fuzztest",
    "startusertestprocess_fuzzer:fuzztest",
    "stateutils_fuzzer:fuzztest",
    "statusbardelegatemanager_fuzzer:fuzztest",
    "statusbardelegatemanagerfirst_fuzzer:fuzztest",
    "statusbardelegatestub_fuzzer:fuzztest",
    "stopserviceability_fuzzer:fuzztest",
    "stopserviceextensionability_fuzzer:fuzztest",
    "stopsyncremotemissions_fuzzer:fuzztest",
    "stopuser_fuzzer:fuzztest",
    "submanagershelper_fuzzer:fuzztest",
    "systemabilitytokencallbackstub_fuzzer:fuzztest",
    # "taskhandlerclient_fuzzer:fuzztest",
    "terminateability_fuzzer:fuzztest",
    "terminatehandler_fuzzer:fuzztest",
    "testobserverstub_fuzzer:fuzztest",
    # "toolstestobserver_fuzzer:fuzztest",
    "uiabilitylifecyclemanagera_fuzzer:fuzztest",
    "uiabilitylifecyclemanagerb_fuzzer:fuzztest",
    "uiextensionrecordfactory_fuzzer:fuzztest",
    "unlockmissionforcleanup_fuzzer:fuzztest",
    "unregisterabilitylifecyclecallback_fuzzer:fuzztest",
    "unregisterapplicationstateobserver_fuzzer:fuzztest",
    "unregisterenvironmentcallback_fuzzer:fuzztest",
    "unregistermissionlistener_fuzzer:fuzztest",
    "updateabilitystate_fuzzer:fuzztest",
    "updatecallerinfoutil_fuzzer:fuzztest",
    "updateconfiguration_fuzzer:fuzztest",
    "updateextensionstate_fuzzer:fuzztest",
    # "uripermissionmanagerclient_fuzzer:fuzztest",
    "uripermissionmanagerstub_fuzzer:fuzztest",
    "uriutils_fuzzer:fuzztest",
    "uriutilsfirst_fuzzer:fuzztest",
    "usercallbackstub_fuzzer:fuzztest",
    "usercontrollerfirst_fuzzer:fuzztest",
    "wantagenthelperstring_fuzzer:fuzztest",
    "wantagenthelpertrigger_fuzzer:fuzztest",
    "wantreceiverstub_fuzzer:fuzztest",
    "wantutils_fuzzer:fuzztest",
    "windowmanagerservicehandlerstub_fuzzer:fuzztest",
    "windowmanagerservicehandlerstubremaining_fuzzer:fuzztest",
    "windowoptionsutils_fuzzer:fuzztest",
  ]
  if (ability_runtime_child_process) {
    deps += [
      "abilitychildprocessinfo_fuzzer:fuzztest",
      "abilitychildprocessrecord_fuzzer:fuzztest",
      "abilitychildprocessrecordfirst_fuzzer:fuzztest",
    ]
  }
  if (ability_runtime_screenlock_enable) {
    deps += [
      "abilityunlockscreencallback_fuzzer:fuzztest",
      "sainterceptorstub_fuzzer:fuzztest",
      "screenunlockinterceptor_fuzzer:fuzztest",
      "screenunlockinterceptorfirst_fuzzer:fuzztest",
    ]
  }
}
